on:
  workflow_dispatch:
    
name: Main

env:
  TF_INPUT: false
  TF_IN_AUTOMATION: true
  TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
  TF_VAR_client_id: ${{ secrets.CLIENT_ID }}
  TF_VAR_tenant_id: ${{ secrets.TENANT_ID }}
  TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
  TF_VAR_principal_id: ${{ secrets.PRINCIPAL_ID }}

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: Plan
    name: Plan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        run: terraform init -backend-config="client_id=${{ secrets.CLIENT_ID }}" -backend-config="client_secret=${{ secrets.CLIENT_SECRET }}" -backend-config="tenant_id=${{ secrets.TENANT_ID }}" -backend-config="subscription_id=${{ secrets.SUBSCRIPTION_ID }}"
      - name: Terraform plan
        run: terraform plan -no-color -out=main.tfplan
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: plan
          path: main.tfplan
          if-no-files-found: error
  apply:
    runs-on: ubuntu-latest
    environment: Apply
    name: Apply
    needs: [plan]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        run: terraform init -backend-config="client_id=${{ secrets.CLIENT_ID }}" -backend-config="client_secret=${{ secrets.CLIENT_SECRET }}" -backend-config="tenant_id=${{ secrets.TENANT_ID }}" -backend-config="subscription_id=${{ secrets.SUBSCRIPTION_ID }}"
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: plan
      - name: Terraform apply
        run: terraform apply main.tfplan
